### 1. 注册接口 (注册一次即可，如果已存在会报错，忽略即可)
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "username": "music_lover_001",
  "password": "123456",
  "nickname": "超级乐迷",
  "email": "test2@example.com"
}

### 2. 登录接口 (【重要】必须先运行这个，才能获取 Token)
# @name login
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "music_lover_001",
  "password": "123456"
}

> {%
    // 脚本：自动把返回的 token 存入全局变量 auth_token
    client.global.set("auth_token", response.body.data.token);
    client.log("获取到的 Token: " + response.body.data.token);
%}

### 3. 获取歌曲列表
GET http://localhost:8080/song/list
# 引用刚才设置的全局变量
Authorization: Bearer {{auth_token}}

### 4. 添加第一首歌 (七里香)
POST http://localhost:8080/song/add
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "title": "七里香",
  "artistId": 1,
  "albumId": 1,
  "fileUrl": "https://music.163.com/song/media/outer/url?id=123.mp3",
  "coverUrl": "https://p1.music.126.net/cover1.jpg",
  "genre": "Pop",
  "duration": 299
}

### 5. 添加第二首歌 (Numb)
POST http://localhost:8080/song/add
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "title": "Numb",
  "artistId": 2,
  "albumId": 2,
  "fileUrl": "https://music.163.com/song/media/outer/url?id=456.mp3",
  "coverUrl": "https://p1.music.126.net/cover2.jpg",
  "genre": "Rock",
  "duration": 187
}

### 6. 创建歌单 "我的最爱"
POST http://localhost:8080/playlist/create
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "title": "我的最爱",
  "description": "这里全是好听的歌"
}

### 7. 把 id=1 的歌(七里香) 加入到 id=1 的歌单里
POST http://localhost:8080/playlist/addSong
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "playlistId": 1,
  "songId": 1
}

### 8. [AI数据] 记录一次“喜欢”行为 (type=3)
POST http://localhost:8080/interaction/record
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "songId": 1,
  "type": 3
}

### 测试 1: 创建歌单 (自动获取 ID)
# @name delete_test_playlist
POST http://localhost:8080/playlist/create
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "title": "待删除歌单",
  "description": "测试删除接口"
}

> {%
    client.global.set("test_playlist_id", response.body.data.id);
%}


### 测试 2: 移除歌单中的一首歌
DELETE http://localhost:8080/playlist/removeSong?playlistId={{test_playlist_id}}&songId=200
Authorization: Bearer {{auth_token}}


### 测试 3: 彻底删除歌单
DELETE http://localhost:8080/playlist/delete/{{test_playlist_id}}
Authorization: Bearer {{auth_token}}